# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "psr-cd-flag-check"
private_key_id = "3b0d35b7335c44217c706f2290a063fb4b0abb63"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChnueC9HYvFs1b
uE30+0pm4RLTSq7WqnxnSkuAq1YgQ9iOZ6YFK4ufHWI7t3YxUkwGHO7puds9bcoY
Bg9J1NVuinOSZDuD6/Kum7nj7PS65PnX+6M4GL9ZMT4SmX+WSGUnbRTa5FIgVv9r
F8TbAayO/LT9+83PA69PfrlHNMXjWOiKH3cSNAh+hz0KRCwDXE4PvtT7KA01Rl6Y
88/AIgwyZzrwRK9cjdwn/D6/WcXMFcNLKr87wTqUcI1bMhMs6pt1ue/Ni0m9v4ha
xljOwdIjyKTg4LJ1A3c6L6fDx2G7sIw/abShBySh+JNXyR1JMHhoiYCzzAazn2Kb
46B06F3fAgMBAAECggEAPzBYhZu8hUad/ak+WXTSLwz6hj+hwe4f+2ZRxLm4T58X
EP43K7hNu2UKnhxpinkJni47vofaztaY9/GOkqgy1igtbWPg3QAn/tqFwDZJrLSP
dkE9HFaYoW+ePDllZ8VgPxzn1XkFHv3EmQNPBO1PoQvuW4rSeYiQRz1dhRh98heV
+EuuN1li/Fl74DzLFI/5Y6Mmzc18k/JstAf66Wr4Ca9B3y/ob5OLR1pvAxRMgN36
TT3T1EOjupn203GBHt8ug/AWs5Bp97qm2TZKqmISc6kp7a1qA6zdogGJCJkZU7s7
AQHj8aQoi6v+sQj6h91Tk8GafjKvbaAZvkUcg0YXmQKBgQDff981nK/rl4A6rUJ4
j1hhrYy5EG5uUVBDGlccXBTu091aL1jAZ/cTzui3a6nerOALJ9FyJohDgnFLxe6X
rjKTQnAWqKcRcKvj/SbBisVg0ooPPVUBiXLBhKVDnBcXMIF8XrgGnWZvPbOSwuaz
pj2EwWmS/bV8oI+2LGoB4WPNYwKBgQC5H37TCbeF+w4ALZUiplRfH9cGxr6XpxN2
6vpY4M9yERCzhRFNubZLtgFzgnO2CMuQHzD3dXs5xJmF97EeRmV+CIVWn/Wy62Nn
lOmOPzaIOC5LE9JFUOKsTxIrOY+uZUrUaKSaG1NQ9B/4zupjyxgp9pTe+fw6CxK3
l3sHxJPkVQKBgQDe9Q9UykRsv6v53RGsd0Nx3dG+ZHflsVRiPIqeDfYL8mqlJwpg
ltZSelyJbev96XNvbX9xYqMYxa4EKyZDRlHJucNbt09DBKVVQRtChA828ZEsdsCw
Uc+a4ZqEAdi/F3J1AYCPiMHBQ0o6pBfFK5e/MbsCGfrMotf6of/2dEQ9hQKBgD9T
wdvJoClKF6EB9tlykrwztSgRRtO0CNmOSnOq++vmYJM4uxGerPi7W0W7Y3/rBE/a
C7MrUisR0P7eG43iwQdbPNnEQJWjJk8hxr+taicxKMzwC+dAYzpUlj+JIlijN/Tv
kxdQr7CqwmEnz1CyAiMgwg6A78KfVRjOzfx7R6g9AoGBAN30JmUjX+FPcjGPRmjr
ipGbOYPnmbfiAjtD3n90IWa4MrHYdSWklZTg6HjmaYPZLCMyAs8t9kVx5TYbW1Pe
FsTzIT0/6Ik42XV1eZoFYsCqJqr180sZ4CcdBTdMEWPXVZbJIUqdPpOrfUkB/Mjc
YK8wV1YJDjojHnrBROM+ZajM
-----END PRIVATE KEY-----
"""
client_email = "psr-cd-lookup@psr-cd-flag-check.iam.gserviceaccount.com"
client_id = "111111232262543539556"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/psr-cd-lookup%40psr-cd-flag-check.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[sheets]
sheet_id = "1J21WFryYV1pGn5bfJuk15onQVVaPscU-8Y71VhEH2DA"
sheet_name = "CD-PSR Flag"  # ⬅️ This should match your sheet tab name exactly
