# .streamlit/secrets.toml

[gcp_service_account]
type = "service_account"
project_id = "psr-cd-flag-check"
private_key_id = "558938abcc0a4a08f284476b6c101ede649d578b"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDRIanB+MDdcI4k\nKPPAusYKIusvy5YGPMsNLj4y4hzrv3y3cn0BegRJ0G6V3Zkj9nCiFLA+nKY4CYOQ\nv4SIH7JtuV3vAhxqiZAM3rQ6lqYjc8p6vhqP7fgEKAv9TKI9z89iHm3T17IXW4I1\nrpCXODB5dbd5hVD/YeHxKqmq9HMqooQtBC7BkWseo+DtYISTmziZxoqtmgR0b7mJ\nJfLX9ifNNBrQYXyNngbnd5omKJG2pEwhGr1bT/oLrADLvXLQJUux8c6orKPKJ4Y2\nVpxoLd4j6xKZeQ+7n5knTkAvH1zbGLlOTniR62LPuEpNtcYVwhGhPFS2TqmXVwMt\nKR60lJhzAgMBAAECggEAARQdXgS8aef0s7cKWsobz12SvPJd2bZijbTZWUXVRFn+\neKu8fU91yjOq/lbgPVE+D3fv2MLSEKPr68kxE8qmDu7PzzXBk8MV3Rsg7tRsEu67\n8pocZPWjO9JBDZNhmtQBi84AXwFTx88PAtvdnwoJJfc3dQb8/fQxSB8iNOGB3oxp\nonXAHubkXe7l25TJXdvgXUb3Wk0/piMqBkc0tYpFrG2ZVDvZ1s+KY/5DvyOkZ0+R\n995VrBPv97S33nXw5AtMYjxNG3u5WzDfJ90J7Wq9wOYv8fNHNI+3C7Nl6lHi5xSy\nbUGHOzKcPdvXIOs1XEQCFA9lP8V3xbQ+UvMe9RX6oQKBgQDySGZlamSNuT9tHeVi\nfrjHKKNpYAWEBzxu3diKGsx/FlLDNi7jRKt5nJQIKt1b5cL2oX0KD2I3AiLp2q6M\nQY1kQoW/KeulvKNKtBbKvIkMYpG/kiD1tH2MPY9D9P52x/jUOiGYV95BlRPxKqSr\nW4ddkhOkbynbd4kBtyjRT/f8CQKBgQDc+MY/ABCjNXnRXWIttgahCqNpDYDYv+Xq\nJRGVnh+mq1AbIyZs2tZgM6u4TY41GBhpna62A4OxIUCzllCHIuZZZdCI1384b84x\n3P1TmPW7TkT+GJhczN+yd8zov5ScodF/n5H/fNJ6Px/QOwxZO3cI1f7MLNlpQqIO\nML24yWTHmwKBgAQPJngIgkrFkcR4PcGasenUSniXfUArBt4spVYbANYYP6a5n6t7\nGQxejTRd03uYq92J8xhaDaEyTfdxDH+ZEY9edfMv9py+PlYgEkmvQvSMKjj1b8vu\nDDRvS5kt352J2CdmGe39euHKZ50gw8WDMQ9mRSH6Is9kf00iDnMDTfpRAoGAZjvO\n9Lzh9bC7EItk7gMmZAGZAvSVZTK7e630ycUjnafq4vNLRtekkVO2ogl3vsbMHKkw\neNN9bUkWN0BXN36FFl1NstII8SKBQn6c0b2WCze2Id1dOKos4NQegJyKdEFFvQcl\ntA+bDaYA4QVAvFQPyY3AWdRyLgn/EhOo40KCFvsCgYB3gOSGXIGoWuxeih0bNhmO\nA5nkTsVSuzQGNYeT+M1WBPcGWB0+Hhkz+VmhBqQqPtPcsen/NpdhoVBWrvUamEAa\nc/Y/zAfznpoq+xvKPYc0B5S+hfg5OQGFkTSiI8lnanoiA6LGsqxy1y1TAy/aOaC3\n9Ttv+elFJ6fFPtlRG4dvlA==
-----END PRIVATE KEY-----
"""
client_email = "cd-psr-check@psr-cd-flag-check.iam.gserviceaccount.com"
client_id = "113138888352875624470"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cd-psr-check%40psr-cd-flag-check.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[sheets]
sheet_id = "1J21WFryYV1pGn5bfJuk15onQVVaPscU-8Y71VhEH2DA"
sheet_name = "CD-PSR Flag"  # ⬅️ This should match your sheet tab name exactly
